apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::338310096871:role/eksctl-eksdemo1-nodegroup-eksdemo1-NodeInstanceRole-vVguJhdmzhle
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-04T03:12:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1510"
  uid: 0953e5ec-c2a0-43e4-8f05-7ac0a87f9dad
